"""
PDF export utility for chat conversations.
"""

from __future__ import annotations

import io
from datetime import datetime


def generate_chat_pdf(messages: list[dict], session_id: str) -> bytes:
    """Generate a PDF from chat messages using reportlab."""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.colors import HexColor
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=50, bottomMargin=50)
        styles = getSampleStyleSheet()

        # Custom styles
        title_style = ParagraphStyle(
            "CustomTitle",
            parent=styles["Title"],
            fontSize=16,
            textColor=HexColor("#1a1a2e"),
        )
        user_style = ParagraphStyle(
            "UserMsg",
            parent=styles["Normal"],
            fontSize=10,
            textColor=HexColor("#2d3748"),
            backColor=HexColor("#e2e8f0"),
            borderPadding=8,
        )
        ai_style = ParagraphStyle(
            "AIMsg",
            parent=styles["Normal"],
            fontSize=10,
            textColor=HexColor("#1a202c"),
            borderPadding=8,
        )

        elements = []

        # Header
        elements.append(Paragraph("KSP Crime Intelligence — Chat Export", title_style))
        elements.append(Spacer(1, 6))
        elements.append(Paragraph(
            f"Session: {session_id[:8]} · Exported: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')} · "
            f"Messages: {len(messages)}",
            styles["Normal"],
        ))
        elements.append(Spacer(1, 20))

        # Messages
        for msg in messages:
            role = msg.get("role", "user")
            content = msg.get("content", "")
            style = user_style if role == "user" else ai_style
            label = "INVESTIGATOR" if role == "user" else "CRIME AI"

            elements.append(Paragraph(f"<b>{label}</b>", styles["Normal"]))
            elements.append(Spacer(1, 4))
            # Clean markdown for PDF
            clean = content.replace("**", "").replace("*", "").replace("#", "")
            elements.append(Paragraph(clean[:2000], style))
            elements.append(Spacer(1, 12))

        # Footer
        elements.append(Spacer(1, 20))
        elements.append(Paragraph(
            "This document is auto-generated by the KSP Crime Intelligence Platform. "
            "AI responses include data citations and are not for judicial use without verification. "
            "All queries are audit logged.",
            ParagraphStyle("Footer", parent=styles["Normal"], fontSize=8, textColor=HexColor("#718096")),
        ))

        doc.build(elements)
        return buffer.getvalue()

    except ImportError:
        # Fallback if reportlab not installed
        return b"PDF generation requires reportlab. Please install it."
